name: Build using script

on:
  push:

jobs:
  build:
    runs-on: "build"

    steps:
    - name: Run on on-demand runner
      run: |
        hostname
        echo "this is on-demand runner #1"

  buildz:
    needs: build
    runs-on: "build"

    steps:
    - name: Run on on-demand runner
      run: |
        hostname
        echo "this is on-demand runner #2"