name: BuildTest

on:
  push:

jobs:
  build:
    runs-on: "scw"

    steps:
      - name: Run on on-demand runner
        run: |
          hostname
          echo "this is on-demand runner #1"

  buildz:
    needs: build
    runs-on: "gcp"

    strategy:
      matrix:
        var:
          - test
          - test3

    steps:
      - name: Run on on-demand runner
        run: |
          hostname
          echo "this is on-demand runner ${{ matrix.var }}"