name: Dispatch Runner
on:
  workflow_run:
    workflows:
      - BuildTest
    types: 
      - requested

jobs:
  tend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.5'

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: 76creates/gh-runner-ctl.git
        ref: main

    - name: Build gh-runner-ctl
      run: |
        go mod tidy
        go mod vendor
        go build -o gh-runner-ctl .
        chmod +x gh-runner-ctl

    - name: watch the job
      run: |
        echo ${{ secrets.RUNNER_CONF }} | ./gh-runner-ctl runner tend -d --github-repo-name=dynamic-runners --github-repo-owner=76creates --github-token=${{ secrets.REPO_TOKEN }} --github-workflow-run-id=${{ github.event.workflow_run.id }}