name: Build

on:
  push:

jobs:
  run-on-demand:
    runs-on: "${{ github.run_id }}-${{ github.job }}"

    steps:
    - name: Run on on-demand runner
      run: |
        hostname
        echo "this is on-demand runner"