name: Build

on:
  push:

jobs:
  wait-for-runners:
    runs-on: ubuntu-latest
    steps:
    - name: print context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Sleep for 3 minutes
      run: |
        echo ${{ github }}
        sleep 180
        
  run-on-demand:
    runs-on: "${{ github.run_id }}"

    steps:
    - name: Run on on-demand runner
      run: |
        hostname
        echo "this is on-demand runner"