name: Workflow Run Trigger

on:
  workflow_run:
    types: 
      - completed
      - requested

jobs:
  printContext:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"